In [1]:
import pandas as pd
df = pd.read_pickle('data/jitline/by_time/changes_complete_buggy_line_level.pkl')
df

,commit_id,idx,changed_type,label,raw_changed_line,changed_line
0,00302787b788c5ff04cb6f62aed5a74d936e86c0,0,added,1,"return GetInput(context, node, index);",return GetInput context node index
1,00302787b788c5ff04cb6f62aed5a74d936e86c0,1,deleted,0,node->inputs->data[i...,node->inputs->data index != kTfLiteOptionalTensor
2,00302787b788c5ff04cb6f62aed5a74d936e86c0,2,deleted,0,if (use_tensor) {,if use_tensor
3,00302787b788c5ff04cb6f62aed5a74d936e86c0,3,deleted,0,"return GetMutableInput(context, node, index);",return GetMutableInput context node index
4,00302787b788c5ff04cb6f62aed5a74d936e86c0,4,deleted,0,},
...,...,...,...,...,...,...
318156,fff90422d181744cd75dbf011687ee7095f02875,328,added,0,ID3D10Multithread_SetMultithreadProtec...,ID<NUM>D<NUM>Multithread_SetMultithreadProtect...
318157,fff90422d181744cd75dbf011687ee7095f02875,329,added,0,ID3D10Multithread_Release(pMultithread);,ID<NUM>D<NUM>Multithread_Release pMultithread
318158,fff90422d181744cd75dbf011687ee7095f02875,330,added,0,},
318159,fff90422d181744cd75dbf011687ee7095f02875,331,added,0,return 0;,return <NUM>
318160,fff90422d181744cd75dbf011687ee7095f02875,332,added,0,},

In [2]:
df = pd.read_pickle('C:/Users/Thinkbook/Downloads/JIT-Fine-master/data/jitline/changes_complete_buggy_line_level.pkl')
df

,commit_hash,idx,changed_type,is_buggy_line,raw_changed_line,code_change_remove_common_tokens
0,6e710a1f78a4a733020a4b2d1f07b6fe4c6684f0,0,added,0.0,throw ioe ;,throw ioe
1,6e710a1f78a4a733020a4b2d1f07b6fe4c6684f0,1,added,0.0,},
2,6e710a1f78a4a733020a4b2d1f07b6fe4c6684f0,2,added,0.0,import java . net . URI ;,import java net URI
3,6e710a1f78a4a733020a4b2d1f07b6fe4c6684f0,3,added,1.0,src = normalize ( src ) ;,src = normalize src
4,6e710a1f78a4a733020a4b2d1f07b6fe4c6684f0,4,added,0.0,} catch ( URISyntaxException e ) {,catch URISyntaxException e
...,...,...,...,...,...,...
327567,7b80edbfe28a488e1bbbe69741ff9f8432a676b8,1,added,0.0,TableDescriptor tableDescriptor = hbaseAdmin ....,TableDescriptor tableDescriptor = hbaseAdmin ...
327568,7b80edbfe28a488e1bbbe69741ff9f8432a676b8,2,added,0.0,import org . apache . hadoop . hbase . client ...,import org apache hadoop hbase client ...
327569,7b80edbfe28a488e1bbbe69741ff9f8432a676b8,3,deleted,0.0,import org . apache . hadoop . hbase . HTableD...,import org apache hadoop hbase HTableD...
327570,7b80edbfe28a488e1bbbe69741ff9f8432a676b8,4,deleted,0.0,HTableDescriptor tableDescriptor = hbaseAdmin ...,HTableDescriptor tableDescriptor = hbaseAdmin ...
327571,7b80edbfe28a488e1bbbe69741ff9f8432a676b8,5,deleted,0.0,get . setTimeStamp ( query . getStartTime ( ) ) ;,get setTimeStamp query getStartTime