In [6]:
import pandas as pd
import pickle
import os

In [7]:
PROJECT = "vccfinder"
VCC_FINDER_CSV = "raw-data/VCCFinder.csv"
TRAIN_TEST_SPLIT_MODE = "cross_project" # by_time/cross_project
TRAIN_TEST_SPLIT_DIR = "raw-data/split_data"
OUTPUT_DIR = f"../data/{PROJECT}/{TRAIN_TEST_SPLIT_MODE}"

In [8]:
# VCC metadata
df = pd.read_csv(VCC_FINDER_CSV)
df = df.drop(columns=['index'])
df

,commit_id,LA,LD,LT,FIX,Entropy,NS,ND,NF,NDEV,AGE,NUC,EXP,REXP,SEXP,count_key_word_add,count_key_word_del,count_key,label
0,c5759e7b76f5bf844be6c6641cc1b356bbc83869,54,44,2660,0,1.080292,1,3,1,1,49.000000,1,0,0.000000,0,18,12,30,0
1,a351091921c8b7d73a7193eaa56933f16c5dfb7f,184,100,3055,1,2.359597,3,3,3,3,24.666667,4,76,373.000000,7,27,8,35,1
2,c5d72beaab1cbbbe68271f4bc4b6670d69985157,72,15,449,1,1.070161,1,1,1,1,114.500000,2,127,572.000000,8,29,2,31,0
3,1a1f5e26a4309480d88598913f9eebf9e9cba8ca,88,83,6129,1,2.147328,1,1,1,24,178.000000,3,4,11.000000,1,103,139,242,0
4,3a849c0c4e42a613f12485a7c5572cea89ab5e19,868,848,7349,1,2.745770,2,2,2,26,116.000000,9,3,6.000000,2,305,305,610,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20269,14f2111f9cec919a450115ce4914f228effca58e,144,184,1922,1,0.851824,2,2,2,0,0.000000,1,377,4171.666667,32,12,15,27,0
20270,f837b6744eb9ca9d8e4f2e93d9118bf787ca5e24,9,5,567,0,0.095205,1,1,1,15,3.000000,1,291,1015.000000,11,1,1,2,0
20271,c7e50b5ef454efd6ab9527d795442c213eeb6afa,76,41,616,1,0.627716,1,1,1,0,0.000000,1,392,1942.666667,1,15,14,29,0
20272,ce891a86763d3540e2612be26938a6163310efe0,13,3,622,0,0.342840,2,2,2,15,5.000000,1,29,138.000000,9,0,0,0,0
20273,032c3339bfb454c65ce38e7eafe49a54bac83073,14,4,1318,0,0.028184,1,1,1,0,0.000000,1,299,1037.000000,12,1,1,2,0

In [9]:
def get_id(data_path='raw-data/split_data', type='by_time'):
    with open(f"{data_path}/{type}/train_ids.txt") as file:
        train_id = [line.rstrip() for line in file]
    with open(f"{data_path}/{type}/test_ids.txt") as file:
        test_id = [line.rstrip() for line in file]
    return train_id, test_id

train_id, test_id = get_id(data_path=TRAIN_TEST_SPLIT_DIR, type=TRAIN_TEST_SPLIT_MODE) 
train, test = df.loc[df['commit_id'].isin(train_id)], df.loc[df['commit_id'].isin(test_id)]
train, test = train.reset_index().drop(columns=['index']), test.reset_index().drop(columns=['index'])

if not os.path.exists(OUTPUT_DIR): 
    os.makedirs(OUTPUT_DIR)
with open(os.path.join(OUTPUT_DIR, "features_train.pkl"), 'wb') as f:
    pickle.dump(train, f)
with open(os.path.join(OUTPUT_DIR, "features_test.pkl"), 'wb') as f:
    pickle.dump(test, f)

In [10]:
df = pickle.load(open(f'{OUTPUT_DIR}/features_test.pkl', 'rb'))
df

,commit_id,LA,LD,LT,FIX,Entropy,NS,ND,NF,NDEV,AGE,NUC,EXP,REXP,SEXP,count_key_word_add,count_key_word_del,count_key,label
0,c5759e7b76f5bf844be6c6641cc1b356bbc83869,54,44,2660,0,1.080292,1,3,1,1,49.0,1,0,0.000000,0,18,12,30,0
1,1a1f5e26a4309480d88598913f9eebf9e9cba8ca,88,83,6129,1,2.147328,1,1,1,24,178.0,3,4,11.000000,1,103,139,242,0
2,3a849c0c4e42a613f12485a7c5572cea89ab5e19,868,848,7349,1,2.745770,2,2,2,26,116.0,9,3,6.000000,2,305,305,610,1
3,0ff832d31470471803b175cfff4e40c1b08ee779,233,31,8224,0,3.003333,2,2,2,2,46.5,3,5,222.000000,1,63,18,81,0
4,6c573e7f33380e60b583294e9ec5d68ae351c3cf,211,98,10646,0,3.626985,1,1,1,2,4.5,2,3,196.000000,1,46,23,69,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3379,14f2111f9cec919a450115ce4914f228effca58e,144,184,1922,1,0.851824,2,2,2,0,0.0,1,377,4171.666667,32,12,15,27,0
3380,f837b6744eb9ca9d8e4f2e93d9118bf787ca5e24,9,5,567,0,0.095205,1,1,1,15,3.0,1,291,1015.000000,11,1,1,2,0
3381,c7e50b5ef454efd6ab9527d795442c213eeb6afa,76,41,616,1,0.627716,1,1,1,0,0.0,1,392,1942.666667,1,15,14,29,0
3382,ce891a86763d3540e2612be26938a6163310efe0,13,3,622,0,0.342840,2,2,2,15,5.0,1,29,138.000000,9,0,0,0,0
3383,032c3339bfb454c65ce38e7eafe49a54bac83073,14,4,1318,0,0.028184,1,1,1,0,0.0,1,299,1037.000000,12,1,1,2,0